### PR TITLE
feat: fix bootstrap 404

### PR DESCRIPTION
**Pull request by fu1996**

### CODE REVIEW

**Comment by Tyriar** [comment]
This is working for me?

image

**Comment by fu1996** [comment]
> This is working for me?
> 
> image

image

In China, it seems impossible to visit

**Review by Tyriar — CHANGES_REQUESTED** [review]
Does https://cdn.jsdelivr.net/npm/bootstrap@3.3.6/dist/css/bootstrap.min.css work in china? That's the officially recommended CDN https://getbootstrap.com/docs/5.2/getting-started/introduction/

**Comment by fu1996** [comment]
> Does https://cdn.jsdelivr.net/npm/bootstrap@3.3.6/dist/css/bootstrap.min.css work in china? That's the officially recommended CDN https://getbootstrap.com/docs/5.2/getting-started/introduction/

Okay, great. I'll fix it
image

**Review by Tyriar — APPROVED** [review]
Thanks 🙂

**Pull request merged**
