### PR TITLE
Expand docs generation to cover addons

### PR DESCRIPTION
**Pull request by pro-src**
* Removes gulp-typedoc which wasn't doing much of anything and is synchronous anyway.
* Renames some categories to help differentiate between the terminal and addons.
* Adjusts the docs transformation (minor file naming stuff) to account for addons.
* Uses the title from _layout/docs.html as it did originally.
* Replaces the old add-on docs

This doesn't contain the examples from the old docs as it's being generated from the source. We might want to defer this update until after https://github.com/xtermjs/xterm.js/issues/1476 is resolved?

### CODE REVIEW

**Comment by pro-src** [comment]
Oops... I forgot to checkout typings/xterm.d.ts before generating the docs. There's a couple of `console.log('test');` that shouldn't be in there. It'll only take a second to rebase and push so you can safely disregard this comment.

**Comment by Tyriar** [comment]
Yes we want to keep the examples, let's do xtermjs/xterm.js#1476 first :+1:

**Comment by pro-src** [comment]
Alright, thanks for the quick response! I know you guys stay busy.

**Comment by pro-src** [comment]
I think that this PR should be closed.

* PR https://github.com/xtermjs/xterm.js/pull/1483 - commit https://github.com/xtermjs/xterm.js/pull/1483/commits/d5af79fc5fde99bd2a01350d80f3d99e1d80feb8 removed the `/// <reference path="..." />` which also removed the ability to generate docs for addons separately from `xterm.d.ts`. Although, once `xterm.d.ts` is published in a separate npm module this won't be an issue.
* Addons will be moved to separate repositories which would at least require cloning multiple repos. This could also be complicated by addons having different `@types` dependencies.

**Comment by pro-src** [comment]
I think each addon repo's README.md would be good enough especially if we generated the docs using a gulpfile (typedoc nothing special) in each repo. A very simple client side script on xtermjs.org could then load the README.md/docs and display it using [marked](https://www.npmjs.com/package/marked). [marked](https://www.npmjs.com/package/marked) would ideally be included by a script tag pointing to a CDN. This way they would have the same site theme as the rest of the docs but remain independent.

**Comment by pro-src** [comment]
Here's an example that display xterm.js's README.md: https://gist.github.com/pro-src/c3085812cbe5a6df066e28c653e4beab
It can previewed via CDN: https://cdn.rawgit.com/pro-src/c3085812cbe5a6df066e28c653e4beab/raw/62cfcaef8cbe4f6f49b27301759b4d5f8fe36452/example.html

**Comment by Tyriar** [comment]
> Addons will be moved to separate repositories which would at least require cloning multiple repos. This could also be complicated by addons having different @types dependencies.

Not necessarily, we could pull in the readme directly? https://raw.githubusercontent.com/xtermjs/xterm.js/master/README.md

> I think each addon repo's README.md would be good enough especially if we generated the docs using a gulpfile (typedoc nothing special) in each repo.

Another option is to just not add addons all together and instead add a list of recommended addons which link to the addon repos which will show their README files? This could strip out a lot of need for tooling in this area.

**Comment by pro-src** [comment]
> Not necessarily, we could pull in the readme directly? https://raw.githubusercontent.com/xtermjs/xterm.js/master/README.md

I don't really see the difference between this option and what I suggested aside from a couple of points.

* You have to update the site whenever you update an add-on.
* It has to be done manually.
* It won't work for the API docs if there is a file tree to consider.

I really mean for this to be about the API docs, not the README.md that would be seen on npmjs/yarn sites.

> Another option is to just not add addons all together and instead add a list of recommended addons which link to the addon repos which will show their README files? This could strip out a lot of need for tooling in this area.

I considered this as well but it makes sense for xtermjs.org to document the addons that xterm.js maintains as opposed to community made add-ons. If it were impractical, I'd lean more that way.

Consider the simplicity of the example. It doesn't need to change much to be a complete solid solution and looks really good on xtermjs.org.

**Comment by pro-src** [comment]
I will be opening a PR for this so it may be seen exactly what's required for the *_marked_* solution.

**Pull request closed without merging**
