### PR TITLE
Generate docs for xtermjs/xterm.js

### PR DESCRIPTION
**Pull request by pro-src**
Closes https://github.com/xtermjs/xterm.js/issues/1455

### CODE REVIEW

**Comment by Tyriar** [comment]
@parisk any comments on the approach would be great when you get a chance

**Comment by pro-src** [comment]
@Tyriar update, the issue was that the typedoc output wasn't being properly adapted for Jekyll. The documents must contain YAML Front Matters and must not be named with a leading underscore to be processed by Jekyll. I wasn't setup to test this properly until now. :sweat_smile: 

I'll be updating this PR with the new changes soon and we'll be able to actually see a full preview. :popcorn:

**Comment by pro-src** [comment]
@parisk @Tyriar , This is ready for review

**Comment by pro-src** [comment]
It's probably a good idea to add the git tag `docs-3.4.0` to either xtermjs/xterm.js@a0e2117819c3ec567bc23e23580442b3260bb85b or the most recent commit after merging. It's not required.

I just remembered that I haven't done anything to update `site.version`. I'll hold off until you guys get a chance to review this.

**Comment by Tyriar** [comment]
@pro-src https://github.com/xtermjs/xterm.js/commit/a0e2117819c3ec567bc23e23580442b3260bb85b is a bad link?

I probably won't be able to review for at least a few days

**Comment by pro-src** [comment]
Nope, the commit is in the current PR and won't be available upstream until after merging.

> I probably won't be able to review for at least a few days

OK.

**Comment by pro-src** [comment]
Awesome

**Comment by pro-src** [comment]
Yep, so you still wouldn't have needed to update this. What was that about maintainability? You guys should focus on maintain contributors. I would still being sending PRs had @Tyriar been more reasonable. Anyways, good luck with that!

**Comment by Tyriar** [comment]
@pro-src you started complaining when we suggested something different, and then you got into a shouting match with one of the contributors https://github.com/xtermjs/xtermjs.org/pull/54#issuecomment-394981609. We dodged a bullet if that's how you behave.

Your legacy is immortalized in the project though with the addition of 
a formal [code of conduct](https://github.com/xtermjs/xterm.js/blob/master/CODE_OF_CONDUCT.md) though 👌

**Comment by pro-src** [comment]
You were shown to be wrong, you're still wrong. The so-called shouting match is where you refused to be wrong. You'd have people believe that I was typing in ALL CAPS and/or was cursing at you. I told you like it was. You didn't dodge a bullet, I was an active and friendly contributor. You lost a team member. That's sad. It's very sad that ***years later*** you're still construing things and denying the truth that you were unreasonable.

My legacy, are you serious? I understand that this hurts your feelings and that you need to control the narrative because you would look bad but my legacy isn't decided by some argument with you? All attempts considered, you were a joke then and you're a joke now.

Enjoy being wrong for as long as these messages exist little man. Your only hope is censorship.

**Comment by Tyriar** [comment]
I said what you did and linked to it. I'm very happy in how things worked out, it would have happened [when you did this](https://twitter.com/sindresorhus/status/1178680301700075522) anyway. I suggest moving on with your life and maybe rethinking some of your values.

**Comment by pro-src** [comment]
Nice try! I'm sure you are very very happy indeed. lol, thanks for spelling out exactly what your problem is but if you want to censor me, I'm not going to let you play it off like that.

**Comment by pro-src** [comment]
I'm a christian so I do believe that it's only natural that we're at odds. ;)

**Pull request merged**
